version: '3.9'

services:
  app:
    build: .
    container_name: dlsec-srv-login
    ports:
      - "8080:8080"   # Ajuste para a porta que sua aplicação usa
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=dlsec

  db:
    image: postgres:15
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dlsec
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
